version: "3.3"

services:

  mysql-db:
    image: mysql:5.6
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'SkiStationDB'
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
    volumes:
      - /home/mysql/data:/home/vagrant/mysql:rw

  springboot-app:

    image: zoghlami19/devopsrepository:latest
    container_name: springboot-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/SkiStationDB?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      MYSQL_HOST: mysql-db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: SkiStationDB
    restart: on-failure
    ports:
      - 8089:8089
    links:
      - mysql-db

  angular-app:

    image: adimoss/angularimage:latest
    container_name: angularimage
    ports:
      - 4200:80
    links:
      - springboot-app